//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FARMER_LIVESTOCK
    {
        public int BaseID { get; set; }
        public int LivestockID { get; set; }
        public int ProductionID { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
