//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FARMER
    {
        public int BaseID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string SupportedBy { get; set; }
        public string SupportSort { get; set; }
        public string Challenges { get; set; }
        public Nullable<System.DateTime> FarmerDateOfBirth { get; set; }
        public Nullable<bool> FormalTraining { get; set; }
        public string FormalHighestEducation { get; set; }
        public string LegalStatusHolding { get; set; }
        public string LRNo { get; set; }
        public Nullable<bool> OtherFarm { get; set; }
        public Nullable<bool> CropSubsistence { get; set; }
        public Nullable<bool> CropSale { get; set; }
        public Nullable<bool> LivestockSubsistence { get; set; }
        public Nullable<bool> LivestockSale { get; set; }
        public Nullable<bool> AquacultureSubsistence { get; set; }
        public Nullable<bool> AquacultureSale { get; set; }
        public Nullable<bool> TreeFarming { get; set; }
        public string CropProductionSystem { get; set; }
        public Nullable<decimal> CropAcreage { get; set; }
        public Nullable<decimal> CropAverageAcreYield { get; set; }
        public Nullable<System.DateTime> DateCropdPlanted { get; set; }
        public string VarietyOfCrop { get; set; }
        public Nullable<bool> UseFertilizer { get; set; }
        public string FertilizerUse { get; set; }
        public Nullable<decimal> AverageFertilizerUse { get; set; }
        public Nullable<decimal> FertilizerSourceDistince { get; set; }
        public string PlaceFertilizerSourced { get; set; }
        public Nullable<bool> SupportOtherCrops { get; set; }
        public string CropChemicalUse { get; set; }
        public string LivestockFeeds { get; set; }
        public string AquacultureType { get; set; }
        public string AquacultureInputs { get; set; }
        public Nullable<bool> FertilizerPonds { get; set; }
        public string AquacultureLevel { get; set; }
        public string PowerSource { get; set; }
        public string FarmLaborSource { get; set; }
        public string FarmStructures { get; set; }
        public string FarmEquipmentOwner { get; set; }
        public string LandManagementPractices { get; set; }
        public string FertilizerTypeUsed { get; set; }
        public Nullable<bool> LimeOnSoil { get; set; }
        public Nullable<bool> SoilTesting { get; set; }
        public string MainWaterSource { get; set; }
        public Nullable<bool> IrrigationDone { get; set; }
        public string TypeOfIrrigation { get; set; }
        public Nullable<decimal> TotalAreaIrrigated { get; set; }
        public string TypeIrrigationProject { get; set; }
        public string IrrigationImplementedBy { get; set; }
        public string SourceFinancialLivehood { get; set; }
        public string FarmerGroupAffiliate { get; set; }
        public string FinancialServices { get; set; }
        public Nullable<bool> InsureCrops { get; set; }
        public Nullable<bool> InsureLivestock { get; set; }
        public Nullable<bool> InsureFarmAssets { get; set; }
        public Nullable<bool> KeepFarmRecords { get; set; }
        public string SourceGAP { get; set; }
        public string MainExtensionProvider { get; set; }
        public string FormatForAdvisories { get; set; }
        public string PreferredTimeAdvisories { get; set; }
        public string PreferredLanguageAdvisories { get; set; }
        public Nullable<decimal> LandAcre { get; set; }
        public string Group_CIG_VGM_PO { get; set; }
        public string Group_Name { get; set; }
        public Nullable<decimal> LeaseYears { get; set; }
        public string VernacularLanguage { get; set; }
    }
}
