//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEALTH_FACILITY
    {
        public int BaseID { get; set; }
        public string FacilityName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Website { get; set; }
        public string Building { get; set; }
        public string County_Code { get; set; }
        public string Sub_County_Code { get; set; }
        public string Constituency_Code { get; set; }
        public string Ward_Code { get; set; }
        public string Level_ID { get; set; }
    }
}
