//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOUSEHOLD
    {
        public int BaseID { get; set; }
        public Nullable<int> HouseHoldTypeId { get; set; }
        public string HouseHoldName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Website { get; set; }
        public string Building { get; set; }
        public string County_Code { get; set; }
        public string Sub_County_Code { get; set; }
        public string Constituency_Code { get; set; }
        public string Ward_Code { get; set; }
        public string Village { get; set; }
        public string LandRegistration { get; set; }
        public Nullable<int> NoWorkers { get; set; }
        public string ContactSurname { get; set; }
        public string ContactFirstname { get; set; }
        public string ContactOthername { get; set; }
        public string ContactGender { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> HouseHoldSize { get; set; }
    }
}
