//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_PROVIDER
    {
        public int ProviderID { get; set; }
        public int userid { get; set; }
        public int ServiceID { get; set; }
        public string Profession { get; set; }
        public string Qualification { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Status { get; set; }
        public string StatusChangedBy { get; set; }
        public Nullable<System.DateTime> StatusChangedOn { get; set; }
    }
}
