//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Aquaculture_ProductionSystem
    {
        public int BaseID { get; set; }
        public int ProductID { get; set; }
        public string ProductSystem { get; set; }
        public Nullable<int> ActiveUnits { get; set; }
        public Nullable<decimal> Area_Volume { get; set; }
        public Nullable<int> InactiveUnits { get; set; }
        public Nullable<decimal> InAcArea_Volume { get; set; }
    }
}
