//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Businesses
    {
        public int BaseID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Pluscode { get; set; }
        public string Category { get; set; }
        public string Address { get; set; }
        public string UserID { get; set; }
        public Nullable<int> BusinessCategory { get; set; }
        public string BusinessName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string Website { get; set; }
        public string Building { get; set; }
        public string County_Code { get; set; }
        public string Constituency_Code { get; set; }
        public string Sub_County_Code { get; set; }
        public string Ward_Code { get; set; }
        public string Expr1 { get; set; }
        public string Sub_County_Name { get; set; }
        public string County_Name { get; set; }
        public string Ward_Name { get; set; }
        public string Constituency_Name { get; set; }
    }
}
