//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Livestock_Feeds
    {
        public int BaseID { get; set; }
        public int FeedID { get; set; }
        public string FeedDescription { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
