//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Livestock_Stock
    {
        public int BaseID { get; set; }
        public int LivestockID { get; set; }
        public string Livestock { get; set; }
        public int ProductionID { get; set; }
        public string ProductionSystem { get; set; }
        public Nullable<int> Stock { get; set; }
    }
}
