//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoAddress.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Schools
    {
        public int BaseID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Pluscode { get; set; }
        public string Category { get; set; }
        public string Address { get; set; }
        public string UserID { get; set; }
        public string NEMIS_CODE { get; set; }
        public string INSTITUTION_NAME { get; set; }
        public string Level_Code { get; set; }
        public string County_Code { get; set; }
        public string Sub_County_Code { get; set; }
        public string Constituency_Code { get; set; }
        public string Ward_Code { get; set; }
    }
}
